# Generated by Django 2.1.3 on 2018-12-01 02:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181129_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='desc_pack',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='包装信息'),
        ),
    ]
